### ISSUE TITLE
Same module can still be opened twice

### ISSUE THREAD

**Issue by badonkadong** [BBasile/dexed#380]
Issue: [#325](https://github.com/BBasile/dexed/issues/325) is still prevalent
To Reproduce:
In your already opened project:
1). Open a source file from the Project Inspector
2). Save Project
3). Close Dexed IDE
4). Open a "dub.json" file with Dexed IDE
5). Open the already opened .d source file from the Project Inspector
this results in two file views of the very same file

**Comment by BBasile** [comment]
Note that i don't say that there is no bug, it's just that i cant reproduce. Maybe try to be more accurate in the repro steps.

**Comment by badonkadong** [comment]
Hey, thanks for the quick response, this made me realise i missinterpreted the missbehaviour 
As for the specification:
Linux x86_64 system with KDE
Dexed IDE 3.6.21

What a did is:
0). Open Dexed IDE executable so that it loads the last opened dub.json project
1). Open a source file from the Project Inspector
2). Menu->File->Save All
3). Close Dexed IDE
4). Open a "dub.json" file with Dexed IDE (as in "dexedide.exe dub.json")
5). Open the already opened .d source file from the Project Inspector
this results in two file views of the very same file

this 100% reproduces the bug, in case it doesn't work as expected, i can capture a recording, maybe it's just me, who knows.

**Comment by BBasile** [comment]
Yes the steps match to what i did already (there was a doubt about 4) and i can't reproduce. I'm on Linux Fedora 28 with KDE as desktop too and i tried with latest release (previously with the devel version). There must be a small detail...

In step 4, do you use a relative or an absolute project filename (i tried with absolute).

**Comment by BBasile** [comment]
You should see in the code editor status bar if one is relative and the other absolute.

**Comment by badonkadong** [comment]
[I made a screencap](https://drive.google.com/file/d/1hYV0DaYrpPgVAFflR-eiwAn1Jvem772p/view?usp=sharing) maybe you'll notice something i can't
as for the relative or absolute, i think dolphin uses absolut paths for the execution

**Comment by BBasile** [comment]
Thanks, i cannot decently ask for more details for now.

**Comment by BBasile** [comment]
The video confirms that it's a relative vs absolute filename issue.

**Comment by BBasile** [comment]
By the way i'm sorry to say that but since i'm also on KDE i know that dexed could look much better.
You can try to install more GTK2 themes (you can even have a full dark theme)

![gtk2_theme](https://user-images.githubusercontent.com/16154339/50039639-b0251e00-0035-11e9-84eb-ee64c2fa9ed0.png)

As editor font i recommend Fira code, which you can select in the "font" section [here](https://bbasile.github.io/dexed/widgets_editor#notable-options).

It's also possible to build dexed for qt4 or qt5 and then it looks even better but you loose the terminal widget (which is a gtk2 only widget)

**Comment by badonkadong** [comment]
Hey, thanks for the tip, i changed the gtk2 theme  to a dark one, 
the problem i have is that the editor setting for the font color gets ignored
![screenshot_20181215_154318](https://user-images.githubusercontent.com/31500722/50044231-a4ab1480-0080-11e9-9394-02244c65ed0a.png)
