### ISSUE TITLE
Cannot close a document

### ISSUE THREAD

**Issue by vporton** [BBasile/dexed#391]
When I click the cross icon near the top right of the window, the currently opened source files is not closed (nothing happens).

"File / Close File" does work.

Dexed 3.7.0

Ubuntu 18.10

**Comment by BBasile** [comment]
Same as #392, sorry.

**Comment by vporton** [comment]
No, this is a different bug than #392, please reopen.

Particularly #392 was solved by fixing `~/.config/dexed` Unix user, but the bug #391 was NOT fixed by this.

**Comment by BBasile** [comment]
The cross ? It's used to close the widget not close document.
To close a document use this one ![](https://raw.githubusercontent.com/BBasile/dexed/master/icons/file/document_delete.png).

**Comment by vporton** [comment]
Yes, I tried to use the cross.
