### ISSUE TITLE
Freeze when pressing : or space on empty auto-complete list.

### ISSUE THREAD

**Issue by mleise** [BBasile/dexed#398]
Type something that triggers the auto-complete window and continue typing until you enter something non-existent, e.g. `import std.aa`. The auto-completion list still shows all modules in `std`. Hit backspace once to delete one 'a'. The auto-completion list is now empty. Hit `:` or space now and the IDE will try to insert the selected entry from the empty list, freezing it in the process.

**Comment by BBasile** [comment]
Indeed, can reproduce.

**Comment by mleise** [comment]
Thanks, that'll make me way less nervous about that save button! (My old habit from Delphi 2005/6 that tended to crash was to casually hit Ctrl+S every 10 seconds.)
