### ISSUE TITLE
Debug with me

### ISSUE THREAD

**Issue by vporton** [BBasile/dexed#407]
Dear BBasile,

I propose you the following endeavor:

Debug with me my D bindings for librdf C libraries (libraptor2, librasqal, librrdf).

It fails with
```
core.exception.InvalidMemoryOperationError@core/exception.d(700): Invalid memory operation
```
after `main()` is completed.

Here is the source of the version I propose to debug together: https://github.com/vporton/redland-bindings/tree/57fd83ead1dabbc730d1a5f68335ebf27481eadb

Do

```
dub build --compiler=ldc2 --config=application --build=unittest
```
in `dlang/` subdir and then run `./rdf_dlang`. It produces this error.

During the endeavor you will gain an understanding of the problems your debugger has. This is useful both for my project and for your project.

**Comment by BBasile** [comment]
yeah i will help for sure, but since that's not related to dexed, not before a [little income of 50€](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=AQDJVC39PJF7J).

**Comment by BBasile** [comment]
you can deactivate the stuff now (3.7.1)
