### ISSUE TITLE
[feature] GDB console is missing

### ISSUE THREAD

**Issue by vporton** [BBasile/dexed#408]
Please make possible to interact with GDB directly (both see its messages) and enter GDB commands.

I see no way for this in Dexed 3.7.0.

**Comment by BBasile** [comment]
The feature is there.

The text field at the bottom is used to enter vustom commands. There is an option the show the raw MI output. When activated this raw output appears in the message widget. {See also a full description of the widget](https://bbasile.github.io/dexed/widgets_gdb_commander). Finally don't forget that [3.7.1 is out now](https://github.com/BBasile/dexed/releases/tag/v3.7.1), it includes the option allowing to deactivate specific core breakpoints.

**Comment by BBasile** [comment]
My doc support anchors, so the paragraph of interest is https://bbasile.github.io/dexed/widgets_gdb_commander#custom-commands

**Comment by vporton** [comment]
The output of `print`/`p` command is not shown (even when I enable showing raw MI output).

See the screenshot where I entered `p 44` command in the bottom of "GDB commander":

![screenshot from 2019-01-18 22-33-21](https://user-images.githubusercontent.com/2900574/51411626-31119100-1b71-11e9-8123-32c0cc040bd4.png)

`44` is not output as it should be.

By the way, what does MI abbr mean?

**Comment by BBasile** [comment]
It's because GDB is working in Machine Interface mode so the output is less CLI friendly, more parser friendly.

**Comment by BBasile** [comment]
The manual is not upd to date so at the right of the toolbar you have a magnifying class icon.
- click on the chevron to its right, to sho the menu, and select "evaluate custom expression"
- click on the icon will show a dialog. Enter the expression here, ok and then in the message you'll se the results.

To do it 100% by hand enter your expression prefixed with `-data-evaluate-expression `
For example `-data-evaluate-expression args.length` if you want to know the length of `args`.

__
 [Learn more about the GDB/MI syntax](https://ftp.gnu.org/old-gnu/Manuals/gdb/html_node/gdb_223.html)

**Comment by vporton** [comment]
Thanks, but it would be great if GDB interactive command syntax was yet available. Is it possible to do?
