### ISSUE TITLE
Floating windows broke

### ISSUE THREAD

**Issue by vporton** [BBasile/dexed#409]
After upgrading to 3.7.1, I have floating windows broke completely.

See the screenshot:

![screenshot from 2019-01-18 17-11-49](https://user-images.githubusercontent.com/2900574/51395042-7bc8e400-1b44-11e9-9dae-3c6d39f4ed2f.png)

**Comment by BBasile** [comment]
Would you have the 3.7.1 html page in cache ? I've delete the changelog by error. Is so please copy and paste the list (or screenshot the changelog).

**Comment by BBasile** [comment]
Version 3.72 is out now : https://github.com/BBasile/dexed/releases/tag/v3.7.2
